service:
  name: node-class-helper

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
  create:
      handler: pets/create.create
      events:
        - http:
            path: pets
            method: post
            cors: true
